### ISSUE TITLE
User can fill out a quick entry for a new client’s dog.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/dog-trainer-app#1]
## 💰 Feature

User can fill out a quick entry for a new client’s dog.

## 🖼 Wireframe

![Screen Shot 2020-12-22 at 1 29 35 PM](https://user-images.githubusercontent.com/71540857/102934863-d3230d80-4459-11eb-9b2e-f9aaa68c1137.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle POST requests at `/api/clients`.
- [x] Create an error response in case the required fields 'Dog's name' and 'Owner's name' are null.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Add the values of the input fields to the state array.
- [x] Refactor the component to send a POST request to '/api/clients' using fetch.
- [x] Complete the component with an event handler for the form.
