### ISSUE TITLE
User can view a list of client dogs.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/dog-trainer-app#2]
## 💰 Feature

User can view a list of client dogs.

## 🖼 Wireframe
![Screen Shot 2020-12-23 at 2 36 00 PM](https://user-images.githubusercontent.com/71540857/103041777-3ed5ab00-452c-11eb-8128-a54f2110f6d4.png)
![Screen Shot 2020-12-23 at 2 39 35 PM](https://user-images.githubusercontent.com/71540857/103041928-b7d50280-452c-11eb-8b4b-4160a058e234.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle GET requests at '/api/clients'.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to get data from the server by sending a GET request to '/api/clients' using fetch .
- [x] Once the response is received and parsed, update the state with the received clients result selecting the following information: dog's name, owner1 and owner2 .
- [x] Update the component to render a list of all clients and to match the wireframe.
- [x] Complete the component to update the state as the user changes the value of the search input field.
- [x] Add a Page Container element to the app.jsx that renders the page according to the hash routing.
- [x] Listen to 'haschange' events on the window and update the state to store the value of the location hash.
- [x] Link the 'Add new' button to the Quick Entry page.

**Comment by vivianevieira** [comment]
## 💰 Feature

User can view a list of clients dogs.

## 🗒️ Notes

This will require me to use ...

## 🖼 Wireframe

![Screen Shot 2020-12-22 at 2 54 24 PM](https://user-images.githubusercontent.com/71540857/102940634-9d842180-4465-11eb-8d19-e0232a1e7db6.png)


## ✅ Tasks

- [ ] Create a route in `server/index.js` to handle GET requests at `/api/clients/`.
- [ ] Test the route with HTTPie.
- [ ] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [ ] Refactor the component to fetch the data from the server.
- [ ] Complete the component with an initial state of ... and an event handler for ...
