### ISSUE TITLE
User can fill out details for client dog.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/dog-trainer-app#3]
## 💰 Feature

User can fill out details for client dog.

## 🖼 Wireframe

![Screen Shot 2020-12-30 at 11 21 05 AM](https://user-images.githubusercontent.com/71540857/103376318-3122a700-4a91-11eb-8af2-b431a7d3ea96.png)
![Screen Shot 2020-12-30 at 11 21 20 AM](https://user-images.githubusercontent.com/71540857/103376320-3253d400-4a91-11eb-8c45-8e70d7257841.png)

## ✅ Tasks

- [x] Add an anchor tag to each client's name on the Client list and add the clientId to the URL route.
- [x] Create a route to handle GET requests at `/api/clients/:clientId`
- [x] Define a component(s) that renders the screen as shown in the wireframe, but with no behavior.
- [x]  Use fetch to send a GET request to `api/clients/${clientId}` and update the State.
- [x] Add value attributes to the form input fields and get the values from the state object.
- [x] Create a route in `server/index.js` to handle PUT requests at `/api/clients/:clientId`.
- [x] Handle any errors.
- [x] Refactor the component to send a PUT request using fetch to `/api/clients/${clientId}`.
- [x] Create a middleware using Multer to handle the file upload.
