### ISSUE TITLE
User can view a dog's profile

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/dog-trainer-app#4]
## 💰 Feature

User can view a dog’s profile.

## 🖼 Wireframe

![Screen Shot 2020-12-31 at 11 50 30 AM](https://user-images.githubusercontent.com/71540857/103423912-6fd26300-4b5e-11eb-80f6-cb967c5e93c8.png)

## ✅ Tasks

- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to submit a GET request to the server at `api/clients/${this.props.clientId}` upon mounting.
- [x] Update the state.
- [x] Update the profile picture to show a preview of the saved image in the case that one has been saved to the user's profile. If not, the image should be a grey circle.
- [x] Link the 'Edit' button to the client's profile edit page.
