### ISSUE TITLE
User can create an entry for a dog's assessment.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/dog-trainer-app#5]
## 💰 Feature

User can create an entry for a dog's assessment.

## 🖼 Wireframe

![Screen Shot 2020-12-31 at 5 01 01 PM](https://user-images.githubusercontent.com/71540857/103431726-d325ba80-4b89-11eb-9216-724b0d67ce41.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle POST requests at `/api/assessment/:clientId`.
- [x] Test the route with HTTPie.
- [x] Create a route in `server/index.js` to handle GET requests at `/api/assessment/:clientId`.
- [x] Define a component that renders the assessment component as shown in the wireframe, but with no behavior.
- [x] Refactor the component to send a GET request to `/api/assessment/${this.props.clientId}` upon mounting using fetch.
- [x] Define a function that returns a list of existing assessment entries.
- [x] Complete the component with an initial state of client data with the clientId matching the client being edited.
- [x] Refactor the component to send a POST request to `/api/assessment/${this.props.clientId}` using fetch upon form submission.
- [x] Add an event handler to handle clicks on the 'Submit' button.
