### ISSUE TITLE
User can upload documents

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/dog-trainer-app#6]
## 💰 Feature

User can upload documents, such as dog’s vaccination records and client contract.

## 🖼 Wireframe

![Screen Shot 2021-01-05 at 3 06 09 PM](https://user-images.githubusercontent.com/71540857/103709545-a1389d80-4f67-11eb-80a9-f356d8b11233.png)
![Screen Shot 2021-01-05 at 3 06 25 PM](https://user-images.githubusercontent.com/71540857/103709547-a3026100-4f67-11eb-91ad-5835b2970fcb.png)

## ✅ Tasks

- [x] Change the upload middleware to handle file uploads using Multer 3 and AWS S3 .
- [x] Test the route with HTTPie.
- [x] Make changes on the route in `server/index.js` that handles PUT requests at `/api/assessment/:clientId` so that it uses the new middleware.
- [x] Update the value of the image URL to be req.file.location (for profile pictures).
- [x] Create a route in `server/index.js` to handle POST requests at `/api/files/:clientId`.
- [x] Test the route with HTTPie.
- [x] Define a new component that renders the 'files' component as shown in the wireframe, but with no behavior.
- [x] Refactor the component to send a POST request to `/api/files/${this.props.clientId}` once the file has been uploaded.
- [x] Create a route in `server/index.js` to handle GET requests at `/api/files/:clientId`.
- [x] Test the route with HTTPie.
- [x] Make changes to the component to send a GET request to /api/files/${this.props.clientId} once it has ben mounted.
- [x] Complete the component with an initial state of client data for files table with the clientId matching the client being viewed.
- [x] Define a function that returns a list of existing files.
