### ISSUE TITLE
User can log communication and notes related to the client dog.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/dog-trainer-app#7]
## 💰 Feature

User can log communication and notes related to the client dog.

## 🖼 Wireframe

![Screen Shot 2021-01-06 at 11 07 38 AM](https://user-images.githubusercontent.com/71540857/103810071-730e9880-500f-11eb-9850-a6f60b1fe9b8.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle POST requests at `/api/notes/:clientId`.
- [x] Test the route with HTTPie.
- [x] Create a route in `server/index.js` to handle GET requests at `/api/notes/:clientId`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the notes section as shown in the wireframe, but with no behavior.
- [x] Refactor the component to send a GET request to `/api/notes/${this.props.clientId}` upon mounting using fetch.
- [x] Complete the component with an initial state of client notes.
- [x] Define a function that returns a list of existing notes entries.
- [x] Refactor the component to send a POST request to `/api/notes/${this.props.clientId}` using fetch once the form has been submitted.
- [x] Create a top nav bar with tabs as shown in the wireframe.
