### ISSUE TITLE
User can add notes to the activity log.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/dog-trainer-app#8]
## 💰 Feature

User can add notes to the activity log.

## 🖼 Wireframe
![Screen Shot 2021-01-07 at 10 48 37 AM](https://user-images.githubusercontent.com/71540857/103931915-ebd82800-50d5-11eb-8cc9-5b6fcb334c37.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle POST requests at `/api/activitylog/:clientId`.
- [x] Test the route with HTTPie.
- [x] Create a route in `server/index.js` to handle GET requests at `/api/activitylog/:clientId`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the activity log section as shown in the wireframe, but with no behavior.
- [x] Refactor the component to send a GET request to `/api/activitylog/${this.props.clientId}` upon mounting using fetch.
- [x] Complete the component with an initial state of client activity log.
- [x] Define a function that returns a list of existing activity log entries.
- [x] Refactor the component to send a POST request to `/api/activitylog/${this.props.clientId}` using fetch once the form has been submitted.
